export const PRODUCTS = [
  {
    id: 0,
    brand: 'BassX',
    title: 'Beats Studio3 Wireless Bluetooth Headphones',
    newPrice: 18.5,
    oldPrice: 22.6,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp8.png',
  },
  {
    id: 1,
    brand: 'Toshiba',
    title: 'Black Walnut Wood &amp; Aluminum Headphone Stand',
    newPrice: 25.6,
    oldPrice: 32.2,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp7.png',
  },
  {
    id: 2,
    brand: 'Apple',
    title: 'T500BT Original Wireless Bluetooth Headphone Deep Bass',
    newPrice: 95.26,
    oldPrice: 96.5,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp6.png',
  },
  {
    id: 3,
    brand: 'Sony',
    title: '4K TV Game Mini Arcade Rocker Condole 32GB/64GB',
    newPrice: 22.51,
    oldPrice: 29.5,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp5.png',
  },
  {
    id: 4,
    brand: 'Samsung',
    title: 'BT918 ANC 35dB Hybrid Active Noise Cancelling',
    newPrice: 125,
    oldPrice: 129.8,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp9.png',
  },
  {
    id: 5,
    brand: 'Google',
    title: 'Cancelling Headset Music Sport Deep Bass',
    newPrice: 23.5,
    oldPrice: 29.5,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp11.png',
  },
  {
    id: 6,
    brand: 'Nikon',
    title: 'Outdoor Waterproof Loudspeaker Stereo Surround Support',
    newPrice: 21.55,
    oldPrice: 27.1,
    image: 'https://agon-nextjs.vercel.app/assets/imgs/page/homepage5/sp4.png',
  },
  {
    id: 7,
    brand: 'Xiaomi',
    title: 'Xiaomi Mi 9T',
    newPrice: 120.5,
    oldPrice: 240.6,
    image:
      'https://cdn.tgdd.vn/Products/Images/42/203053/xiaomi-mi-9t-red-600x600.jpg',
  },
]
